# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python CI # name basically indicates what is my workflow name

# Trigger the workflow on any push to the main branch or pull request
# so to trigger the workflows we need to define some events(like push,pull,merge,delete) based on this event we can trigger a workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

  # then next we go to job
  # we may have multiple job on which we may be running
  # the entire job test cases will be running on unbuntu so basically github provides a container on which we can run the entire application



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
 # step 1: check out the code from the repository
    - name: Check out code
      uses: actions/setup-python@v4 
      with:
        python-version: "3.10"
# step 2: set up python environment
    - name: set up python 
      uses: actions/setup-python@v4 # will again  going to use action which is nothing but the github actions specifically use to create pythion envt
      with:
        python-version: "3.10"
# Step 3: Install dependencies
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pytest pandas  
# if i want to run all test cases i will need all the lib like pytest

# Step 4: Run tests
    - name: Run tests
      run: python -m pytest -q tests # as soon as this particular command is run in the container it will start looking for test folder wherever the specific test folder is there and then it will execute all the unit test casses
